<?php
	echo '<div id="bgimg">';
	echo '<div class="container">';

	if ($heading !== false && $heading !== ""){
		echo '<h3 class="iwt-header">' . $heading . '</h3>';
	}
	if ($subheading !== false && $subheading !== ""){
		echo '<p class="iwt-subheader">' . $subheading . '</p>';
	}

	echo '</div>';
	echo '</div>';

	echo '<style>
            .iwt-header{
                font-size: 30px;
		font-weight: bold;
		padding-top: 20px;
                color: ' . $headercolor . ';
                text-align: ' . $alignment . ';
            }
            .iwt-subheader{
                font-size: 24px;
		font-weight: normal;
                color: ' . $subheadercolor . ';
                text-align: ' . $alignment . ';
	    }
	    #bgimg{
		background-image: url(\'' . $urls[0] . '\');
	    	background-position:center;
		background-size:contain;
		background-repeat:no-repeat;
		height: ' . $height . ';
	    }
        </style>';
?>

